name: Deploy to Fly.io
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" DASHBOARD_KEY="${{ secrets.DASHBOARD_KEY }}" MELONLY_TOKEN="${{ secrets.MELONLY_TOKEN }}" -a osrp-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --local-only -a osrp-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
